version: '3'

# START
# docker-compose up -d
#
# SHUTDOWN
# docker-compose down

services:
  redis:
    image: redis:5.0-stretch
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  redis-data:
